### ISSUE TITLE
webgl2

### ISSUE THREAD

**Issue by whaqzhzd** [deepkolos/shader-graph-wgsl#3]
这个打算支持glsl吗，比如支持cocos creator

**Comment by deepkolos** [comment]
@whaqzhzd glsl 版本内部有开源计划, 不过需要走公司流程了

**Comment by whaqzhzd** [comment]
好吧。

**Comment by deepkolos** [comment]
改成glsl应该不难, 我之前是五一花2天从glsl改成wgsl, 然后开源攒攒star
